### ISSUE TITLE
[SUGGESTION] Export the application's logic out of the main.py file.

### ISSUE THREAD

**Issue by sparkles-laurel** [mehmet-mert/FrameRecorder#11]
In professional programming, it is good to keep the program's logic inside another file. I would like you to do that.

**Comment by mehmet-mert** [comment]
Okay, I will fix it @CadmiumC4 , thank you for your feedback.

**Comment by mehmet-mert** [comment]
> In professional programming, it is good to keep the program's logic inside another file. I would like you to do that.

Thank you for your contribution. I seperated main and interface files.
